[package]
name = "rust_2048"
version = "0.1.0"
authors = ["Jun Ma (WINDOWS) <juma@microsoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
rand_chacha = "0.2.2"
winrt = "0.7"